type Query {
    tickets: [Ticket!]!
}

type Mutation {
    createTicket(input: TicketInput!): Ticket
    updateTicket(id: ID!, input: TicketInput!): Ticket
}

scalar DateTime

type Ticket {
    id: ID!
    title: String
    description: String
    createdAt: DateTime!
    modifiedAt: DateTime
    createdByUserId: ID!
    assignedToUserId: ID
    tagIds: [ID!]!
}

input TicketInput {
    title: String!
    description: String!
    createdByUserId: ID!
    tagIds: [ID!]
}
