type Query {
    users: [User!]!
    userById(id: Int!): User
    usersByIds(ids: [Int!]!): [User!]!
}

type Mutation {
    createUser(input: UserInput!): User
    updateUser(id: Int!, input: UserInput!): User
}

type User {
    id: Int!
    username: String
    name: String
    teamId: Int
}

input UserInput {
    username: String
    name: String
}
