type Query {
    tags: [Tag!]!
    tagById(id: Int!): Tag
    tagsByIds(ids: [Int!]!): [Tag!]!
}

type Mutation {
    createTag(input: TagInput!): Tag
    updateTag(id: Int!, input: TagInput!): Tag
}

type Tag {
    id: Int!
    name: String!
    description: String
}

input TagInput {
    id: Int
    name: String
    description: String
}
